name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Build docs
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      BUN_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Build
        run: bun run build --filter='./apps/docs'

