name: Code

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: [build, eslint, prettier, typescript]
    env:
      BUN_ENV: production
      FORCE_COLOR: 1
      TURBO_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Command
        run: bun run ${{ matrix.command }}

