name: Deploy

on:
  push:
    branches:
      - master

env:
  BUN_ENV: production
  FORCE_COLOR: 1
  TURBO_TELEMETRY_DISABLED: 1
      
permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Tools
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2

      - name: Cache
        uses: rharkor/caching-for-turbo@439abec0d28d21b192fa8817b744ffdf1ee5ac0d # v1.5

      - name: Install
        run: bun install

      - name: Build
        run: bun run build --filter='./apps/starlight'

      - name: Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./apps/starlight/dist/"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      url: ${{ steps.deployment.outputs.page_url }}
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
