name: Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      BUN_ENV: production
      FORCE_COLOR: 1
      TURBO_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Build
        run: bun run build --filter='./apps/docs'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          publish_dir: ./apps/docs/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}

