name: Publish

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      BUN_ENV: production
      FORCE_COLOR: 1
      TURBO_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Tools
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2

      - name: Install
        run: bun install

      - name: Build
        run: bun run build --filter='./packages/**/*'

      - name: Prepublish
        run: bun run prepublish --filter='./packages/**/*'

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --workspaces --provenance --access=public
